### ISSUE TITLE
FireStore

### ISSUE THREAD

**Issue by Perdiga** [terraform-google-modules/terraform-google-cloud-datastore#10]
Is it possible to use this module to create a firestore native. 
As I understood, firestore native is the same as datastore but with a new name

thanks

**Comment by morgante** [comment]
I believe this module should be compatible with Firestore in Datastore mode, but we're looking into larger Firestore support.

**Comment by aaron-lane** [comment]
@Perdiga Does that answer satisfy your question?

**Comment by MateusPD** [comment]
yes thank you
