### ISSUE TITLE
Add support for Terraform v0.12

### ISSUE THREAD

**Issue by pyrossh** [terraform-google-modules/terraform-google-cloud-datastore#11]
I'm getting this error,
```
Error: Unsupported block type

  on .terraform/modules/datastore/terraform-google-modules-terraform-google-cloud-datastore-967e958/main.tf line 28, in resource "null_resource" "cloud-datastore-indices":
  28:   triggers {

Blocks of type "triggers" are not expected here. Did you mean to define
argument "triggers"? If so, use the equals sign to assign it a value.
```
terraform --version
```
Terraform v0.12.2
+ provider.google v2.9.1
+ provider.local v1.2.2
+ provider.null v2.1.2
```

**Comment by morgante** [comment]
Unfortunately this module is not yet updated to support v0.12

**Comment by mike-19** [comment]
This issue still exists 
                           

`Terraform v0.12.24`
`provider.google v3.20.0`
`provider.null v2.1.2`
`provider.random v2.2.1`
 `provider.template v2.1.2`


Error Msg:
`Error: Unsupported block type
  on sa.tf line 23, in resource "null_resource" "format_service_accounts":
  23:   triggers {
Blocks of type "triggers" are not expected here. Did you mean to define
argument "triggers"? If so, use the equals sign to assign it a value.`
